# Docker Services
services:
  # Web Application
  # (https://nuxt.com/)
  webapp:
    build: .
    image: wisegals
    container_name: wisegals
    restart: unless-stopped
    # network_mode: 'host'
    ports:
      - '127.0.0.1:3000:3000'
    #   - '0.0.0.0:80:3000'     # use without proxy server
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    # env_file: .env
    environment:
      - MNEMONIC=${MNEMONIC}
# Networks
networks:
  wisegals-network:
    driver: bridge
